# Generated by Django 2.2.15 on 2020-08-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('Date_of_birth', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Personal_Profile', models.TextField()),
                ('Education', models.TextField()),
                ('Employment_History', models.TextField()),
                ('Achievements', models.TextField()),
                ('Interests', models.TextField()),
                ('Skills', models.TextField()),
                ('References', models.TextField()),
            ],
        ),
    ]
