# Generated by Django 2.2.15 on 2020-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='Email',
            field=models.CharField(default='example@domain.com', max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='Number',
            field=models.CharField(default='xxxxxxxxxxx', max_length=11),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Date_of_birth',
            field=models.CharField(max_length=30),
        ),
    ]
