# Generated by Django 2.2.15 on 2020-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200818_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('Number', models.CharField(default='xxxxxxxxxxx', max_length=11)),
                ('Email', models.CharField(default='example@domain.com', max_length=50)),
                ('Date_of_birth', models.CharField(max_length=30)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Personal_Profile', models.TextField()),
                ('Education', models.TextField()),
                ('Employment_History', models.TextField()),
                ('Achievements', models.TextField()),
                ('Interests', models.TextField()),
                ('Skills', models.TextField()),
                ('References', models.TextField()),
            ],
        ),
    ]
