# Generated by Django 2.2.15 on 2020-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv2',
            name='Date_of_birth',
            field=models.CharField(default='xx/xx/xxxx', max_length=30),
        ),
    ]
